name: Unit and Functional Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: env.yml
          auto-activate-base: false
          activate-environment: ml_project_env
          python-version: "3.9"

      - name: Install Package in Dev Mode
        run: pip install -e .

      - name: Activate Conda environment
        run: |
          eval "$(conda shell.bash hook)"
          conda activate ml_project_env

      - name: Run Pytest
        run: pytest -v tests
